- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.aliases: aliases
    ~/.profile: profile
    ~/.path: path
    ~/.curlrc: curlrc
    ~/.wgetrc: wgetrc
    ~/.gvimrc: gvimrc
    ~/.vimrc: vimrc
    ~/.zshrc: zshrc

