- clean: ["~"]

- shell:
    - "git submodule update --init --recursive external/gws"
    - "git submodule update --init --recursive external/vim-pathogen"
    - "git submodule update --init --recursive external/vim-colors-solarized"
    - "git submodule update --init --recursive external/antigen"
    - "git submodule update --init --recursive external/psql2csv"
    - "mkdir -p ~/src"
    - "mkdir -p ~/.config/gtk-3.0"
    - "mkdir -p ~/.config/Zeal"
    - "mkdir -p ~/.local/bin"
    - "mkdir -p ~/.local/share"
    - "mkdir -p ~/.vim/autoload ~/.vim/bundle ~/.vim/backups ~/.vim/swaps"
    - "rmdir ~/Documents"
    - "rmdir ~/Downloads"
    - "rmdir ~/Pictures"
    - "rmdir ~/Music"
    - "rmdir ~/Videos"
    - "rmdir ~/Templates"
    - "rm ~/.profile"

- link:
    # directories
    "~/Documents": "/media/data/googledrive/daniel@sager1.de/Documents"
    "~/Downloads": "/media/data/downloads"
    "~/Pictures": "/media/data/googledrive/daniel@sager1.de/Pictures"
    "~/Dropbox": "/media/data/Dropbox"
    # dotfiles
    "~/.aliases": "aliases"
    "~/.profile": "profile"
    "~/.gitignore_global": "gitignore_global"
    "~/.gitconfig": "gitconfig"
    "~/.wgetrc": "wgetrc"
    "~/.curlrc": "curlrc"
    "~/.psqlrc": "psqlrc"
    "~/.tmux.conf": "tmux.conf"
    "~/.tmuxinator": "tmuxinator"
    "~/.zshrc": "zshrc"
    # vim
    "~/.vimrc": "vimrc"
    "~/.gvimrc": "gvimrc"
    "~/.vim/autoload/pathogen.vim": "external/vim-pathogen/autoload/pathogen.vim"
    "~/.vim/bundle/vim-colors-solarized": "external/vim-colors-solarized"
    # tools / scripts
    "~/.local/bin/gws": "external/gws/src/gws"
    "~/.local/bin/psql2csv": "external/psql2csv/psql2csv"
    # other config
    "~/.config/redshift.conf": "config/redshift.conf"
    "~/.config/gtk-3.0/settings.ini": "config/gtk-3.0/settings.ini"
    "~/src/.projects.gws": "src/projects.gws"
    "~/.vpnht": "/media/data/home/.vpnht"
    "~/.vagrant.d": "/media/data/home/.vagrant.d"
    "~/.config/Insync": "/media/data/home/.config/Insync"
    "~/.config/Zeal/Zeal.conf": "config/Zeal/Zeal.conf"
