- clean: ["~"]

- shell:
    - "git submodule update --init --recursive external/gws"
    - "git submodule update --init --recursive external/antigen"
    - "mkdir -p ~/src"
    - "mkdir -p ~/.config"
    - "mkdir -p ~/.local/bin"
    - "mkdir -p ~/.local/share"
    - "mkdir -p ~/.local/tools"
    - "mkdir -p ~/.vim/autoload ~/.vim/bundle ~/.vim/backups ~/.vim/swaps"
    - "rm ~/.profile"
    - "rm ~/.aliases"
    - "rm ~/.gitignore_global"
    - "rm ~/.gitconfig"
    - "rm ~/.wgetrc"
    - "rm ~/.curlrc"
    - "rm ~/.psqlrc"
    - "rm ~/.tmux.conf"
    - "rm ~/.tmuxinator"
    - "rm ~/.zshrc"
    - "rm ~/.vimrc"
    - "rm ~/.p10k.zsh"

- link:
    # dotfiles
    "~/.aliases": "aliases"
    "~/.profile": "profile"
    "~/.gitignore_global": "gitignore_global"
    "~/.gitconfig": "gitconfig"
    "~/.wgetrc": "wgetrc"
    "~/.curlrc": "curlrc"
    "~/.psqlrc": "psqlrc"
    "~/.tmux.conf": "tmux.conf"
    "~/.tmuxinator": "tmuxinator"
    "~/.zshrc": "zshrc"
    "~/.vimrc": "vimrc"
    "~/.p10k.zsh": "p10k.zsh"

    # tools / scripts
    "~/.local/bin/gws": "external/gws/src/gws"
    "~/.local/bin/git_delete_stale_branches": "scripts/commands/git_delete_stale_branches.sh"
    "~/.local/bin/clip-image": "scripts/commands/clip_image.sh"

    # other config
    "~/src/.projects.gws": "src/projects.gws"
    "~/.config/nvim": "config/nvim"
    "~/.wezterm.lua": "config/wezterm.lua"
