- clean: ["~"]

- shell:
    - "mkdir -p oh-my-zsh/custom/themes"

- link:
    "~/.dotfiles": ""
    "~/.aliases": "aliases"
    "~/.profile": "profile"
    "~/.path": "path"
    "~/.gitignore_global": "gitignore_global"
    "~/.gitconfig": "gitconfig"
    "~/.curlrc": "curlrc"
    "~/.wgetrc": "wgetrc"
    "~/.gvimrc": "gvimrc"
    "~/.vimrc": "vimrc"
    "~/.zshrc": "zshrc"
    "~/.oh-my-zsh": "oh-my-zsh/"
    "oh-my-zsh/custom/themes/agnoster_custom.zsh-theme": "agnoster_custom.zsh-theme"

