- clean: ["~"]

- shell:
    - "git submodule update --init --recursive external/oh-my-zsh"
    - "mkdir -p external/oh-my-zsh/custom/themes"

- link:
    "~/.dotfiles": ""
    "~/.aliases": "aliases"
    "~/.profile": "profile"
    "~/.path": "path"
    "~/.gitignore_global": "gitignore_global"
    "~/.gitconfig": "gitconfig"
    "~/.wgetrc": "wgetrc"
    "~/.mackup.cfg": "mackup.cfg"
    "~/.curlrc": "curlrc"
    "~/.gvimrc": "gvimrc"
    "~/.vimrc": "vimrc"
    "~/.zshrc": "zshrc"
    "~/.oh-my-zsh": "external/oh-my-zsh/"
    "external/oh-my-zsh/custom/themes/agnoster_custom.zsh-theme": "agnoster_custom.zsh-theme"

