- clean: ["~"]

- shell:
    - "git submodule update --init --recursive external/gws"
    - "git submodule update --init --recursive external/xiki"
    - "git submodule update --init --recursive external/vim-pathogen"
    - "git submodule update --init --recursive external/vim-colors-solarized"
    - "git submodule update --init --recursive external/antigen"
    - "mkdir -p ~/.config"
    - "mkdir -p ~/.local/bin"
    - "mkdir -p ~/.local/share"
    - "mkdir -p ~/src/other"
    - "mkdir -p ~/src/work"
    - "mkdir -p ~/.vim/autoload ~/.vim/bundle ~/.vim/backups ~/.vim/swaps"

- link:
    "~/.dotfiles": ""
    "~/.aliases": "aliases"
    "~/.profile": "profile"
    "~/.gitignore_global": "gitignore_global"
    "~/.gitconfig": "gitconfig"
    "~/.wgetrc": "wgetrc"
    "~/.mackup.cfg": "mackup.cfg"
    "~/.curlrc": "curlrc"
    "~/.gvimrc": "gvimrc"
    "~/.vimrc": "vimrc"
    "~/.tmux.conf": "tmux.conf"
    "~/.tmuxinator": "tmuxinator"
    "~/.vim/autoload/pathogen.vim": "external/vim-pathogen/autoload/pathogen.vim"
    "~/.vim/bundle/vim-colors-solarized": "external/vim-colors-solarized"
    "~/.zshrc": "zshrc"
    "~/.xsh": "xsh"
    "~/.local/bin/gws": "external/gws/src/gws"
    "~/.local/bin/idea.sh": "local/bin/idea.sh"
    "~/.local/share/xiki": "external/xiki"
    "~/.config/redshift.conf": "config/redshift.conf"
    "~/src/.projects.gws": "src/projects.gws"
