- clean: ["~"]

- shell:
    - "git submodule update --init --recursive external/gws"
    - "git submodule update --init --recursive external/antigen"
    - "mkdir -p ~/src"
    - "mkdir -p ~/.config/Zeal"
    - "mkdir -p ~/.local/bin"
    - "mkdir -p ~/.local/share"
    - "mkdir -p ~/.local/tools"
    - "mkdir -p ~/.vim/autoload ~/.vim/bundle ~/.vim/backups ~/.vim/swaps"
    - "rm ~/.profile"
    # - "sudo cp config/etc/sysctl.d/999-inotify-watches.conf /etc/sysctl.d/999-inotify-watches.conf"

- link:
    # directories
    # "~/Documents": "/media/data/googledrive/daniel@sager1.de/Documents"
    # dotfiles
    "~/.aliases": "aliases"
    "~/.profile": "profile"
    "~/.gitignore_global": "gitignore_global"
    "~/.gitconfig": "gitconfig"
    "~/.wgetrc": "wgetrc"
    "~/.curlrc": "curlrc"
    "~/.psqlrc": "psqlrc"
    "~/.tmux.conf": "tmux.conf"
    "~/.tmuxinator": "tmuxinator"
    "~/.zshrc": "zshrc"
    "~/.vimrc": "vimrc"
    "~/.gvimrc": "gvimrc"
    # tools / scripts
    "~/.local/bin/gws": "external/gws/src/gws"
    "~/.local/bin/git_delete_stale_branches": "scripts/commands/git_delete_stale_branches.sh"
    "~/.local/bin/devex_vagrant_tunnel": "scripts/commands/devex_vagrant_tunnel.sh"
    "~/.local/bin/devex_start": "scripts/commands/devex_start.sh"
    "~/.local/bin/update": "scripts/commands/update_system.sh"
    "~/.local/bin/friday_links": "scripts/commands/friday_links.sh"
    # other config
    "~/.config/redshift.conf": "config/redshift.conf"
    "~/.config/bups/config.json": "config/bups/config.json"
    "~/src/.projects.gws": "src/projects.gws"
    # Google drive client https://www.insynchq.com/
    # "~/.config/Insync": "/media/data/home/.config/Insync"
    "~/.config/Zeal/Zeal.conf": "config/Zeal/Zeal.conf"
    "~/.config/autostart/dropboxd.desktop": "config/dropboxd.desktop"
    "~/.config/autostart/dropboxd.desktop": "config/dropboxd.desktop"
    
