- clean: ["~"]

- shell:
    - "git submodule update --init --recursive external/gws"
    - "git submodule update --init --recursive external/xiki"
    - "git submodule update --init --recursive external/vim-pathogen"
    - "git submodule update --init --recursive external/vim-colors-solarized"
    - "git submodule update --init --recursive external/antigen"
    - "mkdir -p ~/.config/variety"
    - "mkdir -p ~/.local/bin"
    - "mkdir -p ~/.local/share"
    - "mkdir -p ~/.vim/autoload ~/.vim/bundle ~/.vim/backups ~/.vim/swaps"
    - "rmdir ~/Documents"
    - "rmdir ~/Downloads"
    - "rmdir ~/Pictures"
    - "rmdir ~/Music"
    - "rmdir ~/Videos"
    - "rmdir ~/Templates"
    - "rm ~/.profile"

- link:
    "~/src": "/media/data/src"
    "~/.aliases": "aliases"
    "~/.profile": "profile"
    "~/.gitignore_global": "gitignore_global"
    "~/.gitconfig": "gitconfig"
    "~/.wgetrc": "wgetrc"
    "~/.curlrc": "curlrc"
    "~/.gvimrc": "gvimrc"
    "~/.psqlrc": "psqlrc"
    "~/.vimrc": "vimrc"
    "~/.tmux.conf": "tmux.conf"
    "~/.tmuxinator": "tmuxinator"
    "~/.vim/autoload/pathogen.vim": "external/vim-pathogen/autoload/pathogen.vim"
    "~/.vim/bundle/vim-colors-solarized": "external/vim-colors-solarized"
    "~/.zshrc": "zshrc"
    "~/.xsh": "xsh"
    "~/.local/bin/gws": "external/gws/src/gws"
    "~/.local/share/xiki": "external/xiki"
    "~/.config/redshift.conf": "config/redshift.conf"
    "~/.config/variety/variety.conf": "config/variety/variety.conf"
    "~/src/.projects.gws": "src/projects.gws"
    "~/Documents": "/media/data/googledrive/daniel@sager1.de/Documents"
    "~/Downloads": "/media/data/downloads"
    "~/Pictures": "/media/data/googledrive/daniel@sager1.de/Pictures"
    "~/Dropbox": "/media/data/Dropbox"
    "~/.vpnht": "/media/data/home/.vpnht"
    "~/.config/Insync": "/media/data/home/.config/Insync"
