- clean: ["~"]

- shell:
    - "git submodule update --init --recursive external/gws"
    - "git submodule update --init --recursive external/oh-my-zsh"
    - "mkdir -p ~/.local/bin"
    - "mkdir -p ~/src/other"
    - "mkdir -p ~/src/work"
    - "mkdir -p external/oh-my-zsh/custom/themes"

- link:
    "~/.dotfiles": ""
    "~/.aliases": "aliases"
    "~/.profile": "profile"
    "~/.gitignore_global": "gitignore_global"
    "~/.gitconfig": "gitconfig"
    "~/.wgetrc": "wgetrc"
    "~/.mackup.cfg": "mackup.cfg"
    "~/.curlrc": "curlrc"
    "~/.gvimrc": "gvimrc"
    "~/.vimrc": "vimrc"
    "~/.zshrc": "zshrc"
    "~/.oh-my-zsh": "external/oh-my-zsh/"
    "external/oh-my-zsh/custom/themes/agnoster_custom.zsh-theme": "agnoster_custom.zsh-theme"
    "~/.local/bin/gws": "external/gws/src/gws"
    "~/src/.projects.gws": "src/projects.gws"
