-- Yendo Cowboy colorscheme
-- Generated from config/yendo-cowboy/palette.yaml — do not edit by hand.
-- Run:  python3 config/yendo-cowboy/generate.py

if vim.g.colors_name then vim.cmd("hi clear") end
vim.g.colors_name = "yendo-cowboy"
vim.o.background = "dark"

-- ── Editor UI ──────────────────────────────────────────────────────────
vim.api.nvim_set_hl(0, "Normal", { fg = "#fff5e1", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "NormalNC", { fg = "#fff5e1", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#fff5e1", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "NormalSB", { fg = "#a0522d", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "FloatBorder", { fg = "#e87530", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "FloatTitle", { fg = "#e87530", bg = "#1a0f0a", bold = true })
vim.api.nvim_set_hl(0, "ColorColumn", { bg = "#0d0704" })
vim.api.nvim_set_hl(0, "Conceal", { fg = "#8b4513" })
vim.api.nvim_set_hl(0, "Cursor", { fg = "#1a0f0a", bg = "#fff5e1" })
vim.api.nvim_set_hl(0, "lCursor", { fg = "#1a0f0a", bg = "#fff5e1" })
vim.api.nvim_set_hl(0, "CursorIM", { fg = "#1a0f0a", bg = "#fff5e1" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#2d1810" })
vim.api.nvim_set_hl(0, "CursorColumn", { bg = "#2d1810" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#e87530", bold = true })
vim.api.nvim_set_hl(0, "LineNr", { fg = "#2d1810" })
vim.api.nvim_set_hl(0, "LineNrAbove", { fg = "#2d1810" })
vim.api.nvim_set_hl(0, "LineNrBelow", { fg = "#2d1810" })
vim.api.nvim_set_hl(0, "SignColumn", { fg = "#2d1810", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "SignColumnSB", { fg = "#2d1810", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "FoldColumn", { fg = "#8b4513", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "Folded", { fg = "#e87530", bg = "#2d1810" })
vim.api.nvim_set_hl(0, "EndOfBuffer", { fg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "VertSplit", { fg = "#a0522d" })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = "#a0522d", bold = true })
vim.api.nvim_set_hl(0, "WinBar", { link = "StatusLine" })
vim.api.nvim_set_hl(0, "WinBarNC", { link = "StatusLineNC" })
vim.api.nvim_set_hl(0, "StatusLine", { fg = "#a0522d", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "StatusLineNC", { fg = "#2d1810", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "TabLine", { fg = "#2d1810", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "TabLineFill", { bg = "#0d0704" })
vim.api.nvim_set_hl(0, "TabLineSel", { fg = "#0d0704", bg = "#e87530" })
vim.api.nvim_set_hl(0, "Visual", { bg = "#2d1810" })
vim.api.nvim_set_hl(0, "VisualNOS", { bg = "#2d1810" })
vim.api.nvim_set_hl(0, "Whitespace", { fg = "#2d1810" })
vim.api.nvim_set_hl(0, "WildMenu", { bg = "#2d1810" })
vim.api.nvim_set_hl(0, "Search", { fg = "#fff5e1", bg = "#3d1e0f" })
vim.api.nvim_set_hl(0, "IncSearch", { fg = "#0d0704", bg = "#e87530" })
vim.api.nvim_set_hl(0, "CurSearch", { link = "IncSearch" })
vim.api.nvim_set_hl(0, "Substitute", { fg = "#0d0704", bg = "#ef5350" })
vim.api.nvim_set_hl(0, "MatchParen", { fg = "#e87530", bold = true })
vim.api.nvim_set_hl(0, "NonText", { fg = "#a0522d" })
vim.api.nvim_set_hl(0, "SpecialKey", { fg = "#a0522d" })
vim.api.nvim_set_hl(0, "Pmenu", { fg = "#fff5e1", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "PmenuSel", { bg = "#3d1e0f" })
vim.api.nvim_set_hl(0, "PmenuSbar", { bg = "#2d1810" })
vim.api.nvim_set_hl(0, "PmenuThumb", { bg = "#2d1810" })
vim.api.nvim_set_hl(0, "PmenuMatch", { fg = "#c4522a", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "PmenuMatchSel", { fg = "#c4522a", bg = "#3d1e0f" })
vim.api.nvim_set_hl(0, "Question", { fg = "#e87530" })
vim.api.nvim_set_hl(0, "QuickFixLine", { bg = "#2d1810", bold = true })
vim.api.nvim_set_hl(0, "ModeMsg", { fg = "#a0522d", bold = true })
vim.api.nvim_set_hl(0, "MsgArea", { fg = "#a0522d" })
vim.api.nvim_set_hl(0, "MoreMsg", { fg = "#e87530" })
vim.api.nvim_set_hl(0, "ErrorMsg", { fg = "#ef5350" })
vim.api.nvim_set_hl(0, "WarningMsg", { fg = "#f5a623" })
vim.api.nvim_set_hl(0, "Directory", { fg = "#e87530" })
vim.api.nvim_set_hl(0, "Title", { fg = "#e87530", bold = true })
vim.api.nvim_set_hl(0, "Bold", { fg = "#fff5e1", bold = true })
vim.api.nvim_set_hl(0, "Italic", { fg = "#fff5e1", italic = true })
vim.api.nvim_set_hl(0, "Underlined", { underline = true })
vim.api.nvim_set_hl(0, "debugPC", { bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "debugBreakpoint", { fg = "#f5a623", bg = "#2d1810" })

-- ── Syntax ─────────────────────────────────────────────────────────────
vim.api.nvim_set_hl(0, "Comment", { fg = "#8b4513", italic = true })
vim.api.nvim_set_hl(0, "Constant", { fg = "#e87530" })
vim.api.nvim_set_hl(0, "String", { fg = "#4caf50" })
vim.api.nvim_set_hl(0, "Character", { fg = "#4caf50" })
vim.api.nvim_set_hl(0, "Number", { fg = "#f5a623" })
vim.api.nvim_set_hl(0, "Float", { fg = "#f5a623" })
vim.api.nvim_set_hl(0, "Boolean", { fg = "#e87530" })
vim.api.nvim_set_hl(0, "Identifier", { fg = "#a0522d" })
vim.api.nvim_set_hl(0, "Function", { fg = "#e87530" })
vim.api.nvim_set_hl(0, "Statement", { fg = "#a0522d" })
vim.api.nvim_set_hl(0, "Conditional", { fg = "#c4522a", italic = true })
vim.api.nvim_set_hl(0, "Repeat", { fg = "#c4522a", italic = true })
vim.api.nvim_set_hl(0, "Label", { fg = "#e87530" })
vim.api.nvim_set_hl(0, "Operator", { fg = "#f5a623" })
vim.api.nvim_set_hl(0, "Keyword", { fg = "#f5a623", italic = true })
vim.api.nvim_set_hl(0, "Exception", { fg = "#ef5350" })
vim.api.nvim_set_hl(0, "PreProc", { fg = "#f5a623" })
vim.api.nvim_set_hl(0, "Include", { fg = "#c4522a" })
vim.api.nvim_set_hl(0, "Define", { fg = "#f5a623" })
vim.api.nvim_set_hl(0, "Macro", { fg = "#f5a623" })
vim.api.nvim_set_hl(0, "PreCondit", { fg = "#f5a623" })
vim.api.nvim_set_hl(0, "Type", { fg = "#c4522a" })
vim.api.nvim_set_hl(0, "StorageClass", { fg = "#c4522a" })
vim.api.nvim_set_hl(0, "Structure", { fg = "#c4522a" })
vim.api.nvim_set_hl(0, "Typedef", { fg = "#c4522a" })
vim.api.nvim_set_hl(0, "Special", { fg = "#c4522a" })
vim.api.nvim_set_hl(0, "SpecialChar", { fg = "#c4522a" })
vim.api.nvim_set_hl(0, "Delimiter", { link = "Special" })
vim.api.nvim_set_hl(0, "Debug", { fg = "#e87530" })
vim.api.nvim_set_hl(0, "Todo", { fg = "#1a0f0a", bg = "#f5a623" })
vim.api.nvim_set_hl(0, "Error", { fg = "#ef5350" })

-- ── Diff ───────────────────────────────────────────────────────────────
vim.api.nvim_set_hl(0, "DiffAdd", { bg = "#1a3d20" })
vim.api.nvim_set_hl(0, "DiffChange", { bg = "#2d1810" })
vim.api.nvim_set_hl(0, "DiffDelete", { bg = "#3d1515" })
vim.api.nvim_set_hl(0, "DiffText", { bg = "#3d1e0f" })
vim.api.nvim_set_hl(0, "diffAdded", { fg = "#4caf50", bg = "#1a3d20" })
vim.api.nvim_set_hl(0, "diffRemoved", { fg = "#ef5350", bg = "#3d1515" })
vim.api.nvim_set_hl(0, "diffChanged", { fg = "#f5a623", bg = "#2d1810" })
vim.api.nvim_set_hl(0, "diffOldFile", { fg = "#c4522a", bg = "#3d1515" })
vim.api.nvim_set_hl(0, "diffNewFile", { fg = "#c4522a", bg = "#1a3d20" })
vim.api.nvim_set_hl(0, "diffFile", { fg = "#e87530" })
vim.api.nvim_set_hl(0, "diffLine", { fg = "#8b4513" })
vim.api.nvim_set_hl(0, "diffIndexLine", { fg = "#a0522d" })

-- ── Spell ──────────────────────────────────────────────────────────────
vim.api.nvim_set_hl(0, "SpellBad", { sp = "#ef5350", undercurl = true })
vim.api.nvim_set_hl(0, "SpellCap", { sp = "#f5a623", undercurl = true })
vim.api.nvim_set_hl(0, "SpellLocal", { sp = "#f5a623", undercurl = true })
vim.api.nvim_set_hl(0, "SpellRare", { sp = "#4caf50", undercurl = true })

-- ── LSP Diagnostics ────────────────────────────────────────────────────
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#ef5350" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#f5a623" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#f5a623" })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#4caf50" })
vim.api.nvim_set_hl(0, "DiagnosticUnnecessary", { fg = "#2d1810" })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", { sp = "#ef5350", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", { sp = "#f5a623", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", { sp = "#f5a623", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", { sp = "#4caf50", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", { fg = "#ef5350", bg = "#2f212a" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarn", { fg = "#f5a623", bg = "#302926" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextInfo", { fg = "#f5a623", bg = "#302926" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextHint", { fg = "#4caf50", bg = "#1f2a2a" })
vim.api.nvim_set_hl(0, "LspReferenceText", { bg = "#2d1810" })
vim.api.nvim_set_hl(0, "LspReferenceRead", { bg = "#2d1810" })
vim.api.nvim_set_hl(0, "LspReferenceWrite", { bg = "#2d1810" })
vim.api.nvim_set_hl(0, "LspCodeLens", { fg = "#8b4513" })
vim.api.nvim_set_hl(0, "LspSignatureActiveParameter", { bg = "#221a1d", bold = true })
vim.api.nvim_set_hl(0, "LspInlayHint", { fg = "#a0522d", bg = "#1e1b24" })
vim.api.nvim_set_hl(0, "LspInfoBorder", { fg = "#e87530", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "healthError", { fg = "#ef5350" })
vim.api.nvim_set_hl(0, "healthSuccess", { fg = "#4caf50" })
vim.api.nvim_set_hl(0, "healthWarning", { fg = "#f5a623" })

-- ── Git Signs ──────────────────────────────────────────────────────────
vim.api.nvim_set_hl(0, "GitSignsAdd", { fg = "#4caf50" })
vim.api.nvim_set_hl(0, "GitSignsChange", { fg = "#f5a623" })
vim.api.nvim_set_hl(0, "GitSignsDelete", { fg = "#ef5350" })

-- ── Treesitter ─────────────────────────────────────────────────────────
vim.api.nvim_set_hl(0, "@comment", { link = "Comment" })
vim.api.nvim_set_hl(0, "@comment.todo", { fg = "#e87530" })
vim.api.nvim_set_hl(0, "@comment.note", { fg = "#4caf50" })
vim.api.nvim_set_hl(0, "@comment.warning", { fg = "#f5a623" })
vim.api.nvim_set_hl(0, "@comment.error", { fg = "#ef5350" })
vim.api.nvim_set_hl(0, "@comment.info", { fg = "#f5a623" })
vim.api.nvim_set_hl(0, "@comment.hint", { fg = "#4caf50" })
vim.api.nvim_set_hl(0, "@boolean", { link = "Boolean" })
vim.api.nvim_set_hl(0, "@number", { link = "Number" })
vim.api.nvim_set_hl(0, "@number.float", { link = "Float" })
vim.api.nvim_set_hl(0, "@string", { link = "String" })
vim.api.nvim_set_hl(0, "@string.regexp", { fg = "#fff5e1" })
vim.api.nvim_set_hl(0, "@string.escape", { fg = "#a0522d" })
vim.api.nvim_set_hl(0, "@string.documentation", { fg = "#e0af68" })
vim.api.nvim_set_hl(0, "@character", { link = "Character" })
vim.api.nvim_set_hl(0, "@character.special", { link = "SpecialChar" })
vim.api.nvim_set_hl(0, "@character.printf", { link = "SpecialChar" })
vim.api.nvim_set_hl(0, "@type", { link = "Type" })
vim.api.nvim_set_hl(0, "@type.builtin", { fg = "#a24729" })
vim.api.nvim_set_hl(0, "@type.definition", { link = "Typedef" })
vim.api.nvim_set_hl(0, "@type.qualifier", { link = "Keyword" })
vim.api.nvim_set_hl(0, "@attribute", { link = "PreProc" })
vim.api.nvim_set_hl(0, "@annotation", { link = "PreProc" })
vim.api.nvim_set_hl(0, "@namespace", { link = "Include" })
vim.api.nvim_set_hl(0, "@module", { link = "Include" })
vim.api.nvim_set_hl(0, "@module.builtin", { fg = "#ef5350" })
vim.api.nvim_set_hl(0, "@namespace.builtin", { link = "@variable.builtin" })
vim.api.nvim_set_hl(0, "@keyword", { fg = "#c4522a", italic = true })
vim.api.nvim_set_hl(0, "@keyword.function", { fg = "#a0522d" })
vim.api.nvim_set_hl(0, "@keyword.operator", { link = "@operator" })
vim.api.nvim_set_hl(0, "@keyword.import", { link = "Include" })
vim.api.nvim_set_hl(0, "@keyword.storage", { link = "StorageClass" })
vim.api.nvim_set_hl(0, "@keyword.repeat", { link = "Repeat" })
vim.api.nvim_set_hl(0, "@keyword.return", { link = "Keyword" })
vim.api.nvim_set_hl(0, "@keyword.exception", { link = "Exception" })
vim.api.nvim_set_hl(0, "@keyword.conditional", { link = "Conditional" })
vim.api.nvim_set_hl(0, "@keyword.coroutine", { link = "Keyword" })
vim.api.nvim_set_hl(0, "@keyword.directive", { link = "PreProc" })
vim.api.nvim_set_hl(0, "@keyword.directive.define", { link = "Define" })
vim.api.nvim_set_hl(0, "@keyword.debug", { link = "Debug" })
vim.api.nvim_set_hl(0, "@variable", { fg = "#fff5e1" })
vim.api.nvim_set_hl(0, "@variable.builtin", { fg = "#ef5350" })
vim.api.nvim_set_hl(0, "@variable.parameter", { fg = "#e0af68" })
vim.api.nvim_set_hl(0, "@variable.parameter.builtin", { fg = "#dab484" })
vim.api.nvim_set_hl(0, "@variable.member", { fg = "#4caf50" })
vim.api.nvim_set_hl(0, "@function", { link = "Function" })
vim.api.nvim_set_hl(0, "@function.builtin", { link = "Special" })
vim.api.nvim_set_hl(0, "@function.call", { link = "@function" })
vim.api.nvim_set_hl(0, "@function.method", { link = "Function" })
vim.api.nvim_set_hl(0, "@function.method.call", { link = "@function.method" })
vim.api.nvim_set_hl(0, "@function.macro", { link = "Macro" })
vim.api.nvim_set_hl(0, "@constructor", { fg = "#a0522d" })
vim.api.nvim_set_hl(0, "@constructor.tsx", { fg = "#c4522a" })
vim.api.nvim_set_hl(0, "@operator", { fg = "#f5a623" })
vim.api.nvim_set_hl(0, "@property", { fg = "#4caf50" })
vim.api.nvim_set_hl(0, "@constant", { link = "Constant" })
vim.api.nvim_set_hl(0, "@constant.builtin", { link = "Special" })
vim.api.nvim_set_hl(0, "@constant.macro", { link = "Define" })
vim.api.nvim_set_hl(0, "@label", { fg = "#e87530" })
vim.api.nvim_set_hl(0, "@tag", { link = "Label" })
vim.api.nvim_set_hl(0, "@tag.javascript", { fg = "#ef5350" })
vim.api.nvim_set_hl(0, "@tag.tsx", { fg = "#ef5350" })
vim.api.nvim_set_hl(0, "@tag.attribute", { link = "@property" })
vim.api.nvim_set_hl(0, "@tag.delimiter", { link = "Delimiter" })
vim.api.nvim_set_hl(0, "@tag.delimiter.tsx", { fg = "#aa5a2d" })
vim.api.nvim_set_hl(0, "@punctuation.delimiter", { fg = "#f5a623" })
vim.api.nvim_set_hl(0, "@punctuation.bracket", { fg = "#a0522d" })
vim.api.nvim_set_hl(0, "@punctuation.special", { fg = "#f5a623" })
vim.api.nvim_set_hl(0, "@punctuation.special.markdown", { fg = "#e87530" })
vim.api.nvim_set_hl(0, "@none", { fg = "#fff5e1" })
vim.api.nvim_set_hl(0, "@diff.plus", { link = "DiffAdd" })
vim.api.nvim_set_hl(0, "@diff.minus", { link = "DiffDelete" })
vim.api.nvim_set_hl(0, "@diff.delta", { link = "DiffChange" })

-- ── Markup ─────────────────────────────────────────────────────────────
vim.api.nvim_set_hl(0, "@markup", { fg = "#fff5e1" })
vim.api.nvim_set_hl(0, "@markup.strong", { bold = true })
vim.api.nvim_set_hl(0, "@markup.italic", { italic = true })
vim.api.nvim_set_hl(0, "@markup.underline", { underline = true })
vim.api.nvim_set_hl(0, "@markup.strikethrough", { fg = "#fff5e1" })
vim.api.nvim_set_hl(0, "@markup.raw", { link = "String" })
vim.api.nvim_set_hl(0, "@markup.raw.markdown_inline", { fg = "#e87530", bg = "#2d1810" })
vim.api.nvim_set_hl(0, "@markup.math", { link = "Special" })
vim.api.nvim_set_hl(0, "@markup.environment", { link = "Macro" })
vim.api.nvim_set_hl(0, "@markup.environment.name", { link = "Type" })
vim.api.nvim_set_hl(0, "@markup.link", { fg = "#4caf50" })
vim.api.nvim_set_hl(0, "@markup.link.label", { link = "SpecialChar" })
vim.api.nvim_set_hl(0, "@markup.link.label.symbol", { link = "Identifier" })
vim.api.nvim_set_hl(0, "@markup.link.url", { link = "Underlined" })
vim.api.nvim_set_hl(0, "@markup.list", { fg = "#f5a623" })
vim.api.nvim_set_hl(0, "@markup.list.markdown", { fg = "#e87530", bold = true })
vim.api.nvim_set_hl(0, "@markup.list.checked", { fg = "#4caf50" })
vim.api.nvim_set_hl(0, "@markup.list.unchecked", { fg = "#e87530" })
vim.api.nvim_set_hl(0, "@markup.emphasis", { italic = true })
vim.api.nvim_set_hl(0, "@markup.heading", { link = "Title" })
vim.api.nvim_set_hl(0, "@markup.heading.1.markdown", { fg = "#e87530", bg = "#2f2427", bold = true })
vim.api.nvim_set_hl(0, "@markup.heading.2.markdown", { fg = "#f5a623", bg = "#302926", bold = true })
vim.api.nvim_set_hl(0, "@markup.heading.3.markdown", { fg = "#4caf50", bg = "#1f2a2a", bold = true })
vim.api.nvim_set_hl(0, "@markup.heading.4.markdown", { fg = "#c4522a", bg = "#2b2126", bold = true })
vim.api.nvim_set_hl(0, "@markup.heading.5.markdown", { fg = "#a0522d", bg = "#272127", bold = true })
vim.api.nvim_set_hl(0, "@markup.heading.6.markdown", { fg = "#fff5e1", bg = "#313139", bold = true })
vim.api.nvim_set_hl(0, "@markup.heading.7.markdown", { fg = "#8b4513", bg = "#251f24", bold = true })
vim.api.nvim_set_hl(0, "@markup.heading.8.markdown", { fg = "#ef5350", bg = "#2f212a", bold = true })
vim.api.nvim_set_hl(0, "htmlH1", { fg = "#a0522d", bold = true })
vim.api.nvim_set_hl(0, "htmlH2", { fg = "#e87530", bold = true })
vim.api.nvim_set_hl(0, "helpExample", { fg = "#8b4513" })
vim.api.nvim_set_hl(0, "helpCommand", { fg = "#e87530", bg = "#2d1810" })
vim.api.nvim_set_hl(0, "qfFileName", { fg = "#e87530" })
vim.api.nvim_set_hl(0, "qfLineNr", { fg = "#8b4513" })
vim.api.nvim_set_hl(0, "dosIniLabel", { link = "@property" })

-- ── LSP Semantic Tokens ────────────────────────────────────────────────
vim.api.nvim_set_hl(0, "@lsp.type.boolean", { link = "@boolean" })
vim.api.nvim_set_hl(0, "@lsp.type.builtinType", { link = "@type.builtin" })
vim.api.nvim_set_hl(0, "@lsp.type.comment", { link = "@comment" })
vim.api.nvim_set_hl(0, "@lsp.type.decorator", { link = "@attribute" })
vim.api.nvim_set_hl(0, "@lsp.type.enum", { link = "@type" })
vim.api.nvim_set_hl(0, "@lsp.type.enumMember", { link = "@constant" })
vim.api.nvim_set_hl(0, "@lsp.type.escapeSequence", { link = "@string.escape" })
vim.api.nvim_set_hl(0, "@lsp.type.formatSpecifier", { link = "@markup.list" })
vim.api.nvim_set_hl(0, "@lsp.type.generic", { link = "@variable" })
vim.api.nvim_set_hl(0, "@lsp.type.interface", { fg = "#c37667" })
vim.api.nvim_set_hl(0, "@lsp.type.keyword", { link = "@keyword" })
vim.api.nvim_set_hl(0, "@lsp.type.lifetime", { link = "@keyword.storage" })
vim.api.nvim_set_hl(0, "@lsp.type.namespace", { link = "@module" })
vim.api.nvim_set_hl(0, "@lsp.type.namespace.python", { link = "@variable" })
vim.api.nvim_set_hl(0, "@lsp.type.number", { link = "@number" })
vim.api.nvim_set_hl(0, "@lsp.type.operator", { link = "@operator" })
vim.api.nvim_set_hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
vim.api.nvim_set_hl(0, "@lsp.type.property", { link = "@property" })
vim.api.nvim_set_hl(0, "@lsp.type.selfKeyword", { link = "@variable.builtin" })
vim.api.nvim_set_hl(0, "@lsp.type.selfTypeKeyword", { link = "@variable.builtin" })
vim.api.nvim_set_hl(0, "@lsp.type.string", { link = "@string" })
vim.api.nvim_set_hl(0, "@lsp.type.struct", { link = "@type" })
vim.api.nvim_set_hl(0, "@lsp.type.typeAlias", { link = "@type.definition" })
vim.api.nvim_set_hl(0, "@lsp.type.unresolvedReference", { sp = "#ef5350", undercurl = true })
vim.api.nvim_set_hl(0, "@lsp.type.variable", {  })
vim.api.nvim_set_hl(0, "@lsp.type.deriveHelper", { link = "@attribute" })
vim.api.nvim_set_hl(0, "@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
vim.api.nvim_set_hl(0, "@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
vim.api.nvim_set_hl(0, "@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
vim.api.nvim_set_hl(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
vim.api.nvim_set_hl(0, "@lsp.typemod.keyword.async", { link = "@keyword.coroutine" })
vim.api.nvim_set_hl(0, "@lsp.typemod.keyword.injected", { link = "@keyword" })
vim.api.nvim_set_hl(0, "@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
vim.api.nvim_set_hl(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
vim.api.nvim_set_hl(0, "@lsp.typemod.operator.injected", { link = "@operator" })
vim.api.nvim_set_hl(0, "@lsp.typemod.string.injected", { link = "@string" })
vim.api.nvim_set_hl(0, "@lsp.typemod.struct.defaultLibrary", { link = "@type.builtin" })
vim.api.nvim_set_hl(0, "@lsp.typemod.type.defaultLibrary", { fg = "#a24729" })
vim.api.nvim_set_hl(0, "@lsp.typemod.typeAlias.defaultLibrary", { fg = "#a24729" })
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.callable", { link = "@function" })
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.injected", { link = "@variable" })
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.static", { link = "@constant" })

-- ── Plugin: Blink / Completion ─────────────────────────────────────────
vim.api.nvim_set_hl(0, "BlinkCmpDoc", { fg = "#fff5e1", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "BlinkCmpDocBorder", { fg = "#e87530", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "BlinkCmpGhostText", { fg = "#2d1810" })
vim.api.nvim_set_hl(0, "BlinkCmpLabel", { fg = "#fff5e1", bg = "NONE" })
vim.api.nvim_set_hl(0, "BlinkCmpLabelDeprecated", { fg = "#2d1810", bg = "NONE" })
vim.api.nvim_set_hl(0, "BlinkCmpLabelMatch", { fg = "#c4522a", bg = "NONE" })
vim.api.nvim_set_hl(0, "BlinkCmpMenu", { fg = "#fff5e1", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "BlinkCmpMenuBorder", { fg = "#e87530", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "BlinkCmpSignatureHelp", { fg = "#fff5e1", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "BlinkCmpSignatureHelpBorder", { fg = "#e87530", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "BlinkCmpKindDefault", { fg = "#a0522d", bg = "NONE" })
vim.api.nvim_set_hl(0, "BlinkCmpKindCodeium", { fg = "#4caf50", bg = "NONE" })
vim.api.nvim_set_hl(0, "BlinkCmpKindCopilot", { fg = "#4caf50", bg = "NONE" })
vim.api.nvim_set_hl(0, "BlinkCmpKindSupermaven", { fg = "#4caf50", bg = "NONE" })
vim.api.nvim_set_hl(0, "BlinkCmpKindTabNine", { fg = "#4caf50", bg = "NONE" })
vim.api.nvim_set_hl(0, "BlinkCmpKindText", { link = "LspKindText" })
vim.api.nvim_set_hl(0, "BlinkCmpKindFunction", { link = "LspKindFunction" })
vim.api.nvim_set_hl(0, "BlinkCmpKindKeyword", { link = "LspKindKeyword" })
vim.api.nvim_set_hl(0, "BlinkCmpKindField", { link = "LspKindField" })
vim.api.nvim_set_hl(0, "BlinkCmpKindVariable", { link = "LspKindVariable" })
vim.api.nvim_set_hl(0, "BlinkCmpKindClass", { link = "LspKindClass" })
vim.api.nvim_set_hl(0, "BlinkCmpKindInterface", { link = "LspKindInterface" })
vim.api.nvim_set_hl(0, "BlinkCmpKindModule", { link = "LspKindModule" })
vim.api.nvim_set_hl(0, "BlinkCmpKindProperty", { link = "LspKindProperty" })
vim.api.nvim_set_hl(0, "BlinkCmpKindUnit", { link = "LspKindUnit" })
vim.api.nvim_set_hl(0, "BlinkCmpKindValue", { link = "LspKindValue" })
vim.api.nvim_set_hl(0, "BlinkCmpKindEnum", { link = "LspKindEnum" })
vim.api.nvim_set_hl(0, "BlinkCmpKindColor", { link = "LspKindColor" })
vim.api.nvim_set_hl(0, "BlinkCmpKindConstant", { link = "LspKindConstant" })
vim.api.nvim_set_hl(0, "BlinkCmpKindConstructor", { link = "LspKindConstructor" })
vim.api.nvim_set_hl(0, "BlinkCmpKindEnumMember", { link = "LspKindEnumMember" })
vim.api.nvim_set_hl(0, "BlinkCmpKindEvent", { link = "LspKindEvent" })
vim.api.nvim_set_hl(0, "BlinkCmpKindFile", { link = "LspKindFile" })
vim.api.nvim_set_hl(0, "BlinkCmpKindFolder", { link = "LspKindFolder" })
vim.api.nvim_set_hl(0, "BlinkCmpKindMethod", { link = "LspKindMethod" })
vim.api.nvim_set_hl(0, "BlinkCmpKindNamespace", { link = "LspKindNamespace" })
vim.api.nvim_set_hl(0, "BlinkCmpKindNull", { link = "LspKindNull" })
vim.api.nvim_set_hl(0, "BlinkCmpKindNumber", { link = "LspKindNumber" })
vim.api.nvim_set_hl(0, "BlinkCmpKindObject", { link = "LspKindObject" })
vim.api.nvim_set_hl(0, "BlinkCmpKindOperator", { link = "LspKindOperator" })
vim.api.nvim_set_hl(0, "BlinkCmpKindPackage", { link = "LspKindPackage" })
vim.api.nvim_set_hl(0, "BlinkCmpKindReference", { link = "LspKindReference" })
vim.api.nvim_set_hl(0, "BlinkCmpKindSnippet", { link = "LspKindSnippet" })
vim.api.nvim_set_hl(0, "BlinkCmpKindString", { link = "LspKindString" })
vim.api.nvim_set_hl(0, "BlinkCmpKindStruct", { link = "LspKindStruct" })
vim.api.nvim_set_hl(0, "BlinkCmpKindTypeParameter", { link = "LspKindTypeParameter" })
vim.api.nvim_set_hl(0, "BlinkCmpKindArray", { link = "LspKindArray" })
vim.api.nvim_set_hl(0, "BlinkCmpKindBoolean", { link = "LspKindBoolean" })

-- ── Plugin: LspKind icons ──────────────────────────────────────────────
vim.api.nvim_set_hl(0, "LspKindText", { link = "@markup" })
vim.api.nvim_set_hl(0, "LspKindFunction", { link = "@function" })
vim.api.nvim_set_hl(0, "LspKindKeyword", { link = "@lsp.type.keyword" })
vim.api.nvim_set_hl(0, "LspKindField", { link = "@variable.member" })
vim.api.nvim_set_hl(0, "LspKindVariable", { link = "@variable" })
vim.api.nvim_set_hl(0, "LspKindClass", { link = "@type" })
vim.api.nvim_set_hl(0, "LspKindInterface", { link = "@lsp.type.interface" })
vim.api.nvim_set_hl(0, "LspKindModule", { link = "@module" })
vim.api.nvim_set_hl(0, "LspKindProperty", { link = "@property" })
vim.api.nvim_set_hl(0, "LspKindUnit", { link = "@lsp.type.struct" })
vim.api.nvim_set_hl(0, "LspKindValue", { link = "@string" })
vim.api.nvim_set_hl(0, "LspKindEnum", { link = "@lsp.type.enum" })
vim.api.nvim_set_hl(0, "LspKindColor", { link = "Special" })
vim.api.nvim_set_hl(0, "LspKindConstant", { link = "@constant" })
vim.api.nvim_set_hl(0, "LspKindConstructor", { link = "@constructor" })
vim.api.nvim_set_hl(0, "LspKindEnumMember", { link = "@lsp.type.enumMember" })
vim.api.nvim_set_hl(0, "LspKindEvent", { link = "Special" })
vim.api.nvim_set_hl(0, "LspKindFile", { link = "Normal" })
vim.api.nvim_set_hl(0, "LspKindFolder", { link = "Directory" })
vim.api.nvim_set_hl(0, "LspKindMethod", { link = "@function.method" })
vim.api.nvim_set_hl(0, "LspKindNamespace", { link = "@module" })
vim.api.nvim_set_hl(0, "LspKindNull", { link = "@constant.builtin" })
vim.api.nvim_set_hl(0, "LspKindNumber", { link = "@number" })
vim.api.nvim_set_hl(0, "LspKindObject", { link = "@constant" })
vim.api.nvim_set_hl(0, "LspKindOperator", { link = "@operator" })
vim.api.nvim_set_hl(0, "LspKindPackage", { link = "@module" })
vim.api.nvim_set_hl(0, "LspKindReference", { link = "@markup.link" })
vim.api.nvim_set_hl(0, "LspKindSnippet", { link = "Conceal" })
vim.api.nvim_set_hl(0, "LspKindString", { link = "@string" })
vim.api.nvim_set_hl(0, "LspKindStruct", { link = "@lsp.type.struct" })
vim.api.nvim_set_hl(0, "LspKindTypeParameter", { link = "@lsp.type.typeParameter" })
vim.api.nvim_set_hl(0, "LspKindArray", { link = "@punctuation.bracket" })
vim.api.nvim_set_hl(0, "LspKindBoolean", { link = "@boolean" })

-- ── Plugin: Noice ──────────────────────────────────────────────────────
vim.api.nvim_set_hl(0, "NoiceCmdlineIconInput", { fg = "#e0af68" })
vim.api.nvim_set_hl(0, "NoiceCmdlineIconLua", { fg = "#c4522a" })
vim.api.nvim_set_hl(0, "NoiceCmdlinePopupBorderInput", { fg = "#e0af68" })
vim.api.nvim_set_hl(0, "NoiceCmdlinePopupBorderLua", { fg = "#c4522a" })
vim.api.nvim_set_hl(0, "NoiceCmdlinePopupTitleInput", { fg = "#e0af68" })
vim.api.nvim_set_hl(0, "NoiceCmdlinePopupTitleLua", { fg = "#c4522a" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindDefault", { fg = "#a0522d", bg = "NONE" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindArray", { link = "LspKindArray" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindBoolean", { link = "LspKindBoolean" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindClass", { link = "LspKindClass" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindColor", { link = "LspKindColor" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindConstant", { link = "LspKindConstant" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindConstructor", { link = "LspKindConstructor" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindEnum", { link = "LspKindEnum" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindEnumMember", { link = "LspKindEnumMember" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindEvent", { link = "LspKindEvent" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindField", { link = "LspKindField" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindFile", { link = "LspKindFile" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindFolder", { link = "LspKindFolder" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindFunction", { link = "LspKindFunction" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindInterface", { link = "LspKindInterface" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindKey", { link = "LspKindKey" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindKeyword", { link = "LspKindKeyword" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindMethod", { link = "LspKindMethod" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindModule", { link = "LspKindModule" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindNamespace", { link = "LspKindNamespace" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindNull", { link = "LspKindNull" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindNumber", { link = "LspKindNumber" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindObject", { link = "LspKindObject" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindOperator", { link = "LspKindOperator" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindPackage", { link = "LspKindPackage" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindProperty", { link = "LspKindProperty" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindReference", { link = "LspKindReference" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindSnippet", { link = "LspKindSnippet" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindString", { link = "LspKindString" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindStruct", { link = "LspKindStruct" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindText", { link = "LspKindText" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindTypeParameter", { link = "LspKindTypeParameter" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindUnit", { link = "LspKindUnit" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindValue", { link = "LspKindValue" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindVariable", { link = "LspKindVariable" })

-- ── Plugin: Snacks ─────────────────────────────────────────────────────
vim.api.nvim_set_hl(0, "SnacksDashboardDesc", { fg = "#f5a623" })
vim.api.nvim_set_hl(0, "SnacksDashboardDir", { fg = "#a0522d" })
vim.api.nvim_set_hl(0, "SnacksDashboardFooter", { fg = "#c4522a" })
vim.api.nvim_set_hl(0, "SnacksDashboardHeader", { fg = "#e87530" })
vim.api.nvim_set_hl(0, "SnacksDashboardIcon", { fg = "#c4522a" })
vim.api.nvim_set_hl(0, "SnacksDashboardKey", { fg = "#e87530" })
vim.api.nvim_set_hl(0, "SnacksDashboardSpecial", { fg = "#c4522a" })
vim.api.nvim_set_hl(0, "SnacksIndent", { fg = "#2d1810", nocombine = true })
vim.api.nvim_set_hl(0, "SnacksIndent1", { fg = "#e87530", nocombine = true })
vim.api.nvim_set_hl(0, "SnacksIndent2", { fg = "#f5a623", nocombine = true })
vim.api.nvim_set_hl(0, "SnacksIndent3", { fg = "#4caf50", nocombine = true })
vim.api.nvim_set_hl(0, "SnacksIndent4", { fg = "#c4522a", nocombine = true })
vim.api.nvim_set_hl(0, "SnacksIndent5", { fg = "#a0522d", nocombine = true })
vim.api.nvim_set_hl(0, "SnacksIndent6", { fg = "#fff5e1", nocombine = true })
vim.api.nvim_set_hl(0, "SnacksIndent7", { fg = "#8b4513", nocombine = true })
vim.api.nvim_set_hl(0, "SnacksIndent8", { fg = "#ef5350", nocombine = true })
vim.api.nvim_set_hl(0, "SnacksIndentScope", { fg = "#c4522a", nocombine = true })
vim.api.nvim_set_hl(0, "SnacksZenIcon", { fg = "#c4522a" })
vim.api.nvim_set_hl(0, "SnacksInputIcon", { fg = "#c4522a" })
vim.api.nvim_set_hl(0, "SnacksInputBorder", { fg = "#e0af68" })
vim.api.nvim_set_hl(0, "SnacksInputTitle", { fg = "#e0af68" })
vim.api.nvim_set_hl(0, "SnacksGhLabel", { fg = "#c4522a", bold = true })
vim.api.nvim_set_hl(0, "SnacksDiffLabel", { fg = "#c4522a", bold = true })
vim.api.nvim_set_hl(0, "SnacksGhDiffHeader", { fg = "#c4522a", bg = "#2b2126" })
vim.api.nvim_set_hl(0, "SnacksPickerBoxTitle", { fg = "#e87530", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "SnacksPickerInputBorder", { fg = "#e87530", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "SnacksPickerInputTitle", { fg = "#e87530", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "SnacksPickerSelected", { fg = "#ef5350" })
vim.api.nvim_set_hl(0, "SnacksPickerToggle", { link = "SnacksProfilerBadgeInfo" })
vim.api.nvim_set_hl(0, "SnacksPickerPickWin", { fg = "#fff5e1", bg = "#3d1e0f", bold = true })
vim.api.nvim_set_hl(0, "SnacksPickerPickWinCurrent", { fg = "#fff5e1", bg = "#ef5350", bold = true })
vim.api.nvim_set_hl(0, "SnacksProfilerIconInfo", { fg = "#c4522a", bg = "#4d2c27" })
vim.api.nvim_set_hl(0, "SnacksProfilerBadgeInfo", { fg = "#c4522a", bg = "#2b2126" })
vim.api.nvim_set_hl(0, "SnacksFooterKey", { link = "SnacksProfilerIconInfo" })
vim.api.nvim_set_hl(0, "SnacksFooterDesc", { link = "SnacksProfilerBadgeInfo" })
vim.api.nvim_set_hl(0, "SnacksProfilerIconTrace", { fg = "#a0522d", bg = "#251c1f" })
vim.api.nvim_set_hl(0, "SnacksProfilerBadgeTrace", { fg = "#a0522d", bg = "#1e1b24" })
vim.api.nvim_set_hl(0, "SnacksNotifierDebug", { fg = "#fff5e1", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "SnacksNotifierBorderDebug", { fg = "#472c1e", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "SnacksNotifierIconDebug", { fg = "#8b4513" })
vim.api.nvim_set_hl(0, "SnacksNotifierTitleDebug", { fg = "#8b4513" })
vim.api.nvim_set_hl(0, "SnacksNotifierError", { fg = "#fff5e1", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "SnacksNotifierBorderError", { fg = "#6f3137", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "SnacksNotifierIconError", { fg = "#ef5350" })
vim.api.nvim_set_hl(0, "SnacksNotifierTitleError", { fg = "#ef5350" })
vim.api.nvim_set_hl(0, "SnacksNotifierInfo", { fg = "#fff5e1", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "SnacksNotifierBorderInfo", { fg = "#725325", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "SnacksNotifierIconInfo", { fg = "#f5a623" })
vim.api.nvim_set_hl(0, "SnacksNotifierTitleInfo", { fg = "#f5a623" })
vim.api.nvim_set_hl(0, "SnacksNotifierTrace", { fg = "#fff5e1", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "SnacksNotifierBorderTrace", { fg = "#5e3128", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "SnacksNotifierIconTrace", { fg = "#c4522a" })
vim.api.nvim_set_hl(0, "SnacksNotifierTitleTrace", { fg = "#c4522a" })
vim.api.nvim_set_hl(0, "SnacksNotifierWarn", { fg = "#fff5e1", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "SnacksNotifierBorderWarn", { fg = "#725325", bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "SnacksNotifierIconWarn", { fg = "#f5a623" })
vim.api.nvim_set_hl(0, "SnacksNotifierTitleWarn", { fg = "#f5a623" })

-- ── Plugin: Which-key ───────────────────────────────────────────────────
vim.api.nvim_set_hl(0, "WhichKey", { fg = "#f5a623" })
vim.api.nvim_set_hl(0, "WhichKeyGroup", { fg = "#e87530" })
vim.api.nvim_set_hl(0, "WhichKeyDesc", { fg = "#a0522d" })
vim.api.nvim_set_hl(0, "WhichKeySeparator", { fg = "#8b4513" })
vim.api.nvim_set_hl(0, "WhichKeyNormal", { bg = "#1a0f0a" })
vim.api.nvim_set_hl(0, "WhichKeyValue", { fg = "#8b4513" })

-- ── Plugin: Trouble ────────────────────────────────────────────────────
vim.api.nvim_set_hl(0, "TroubleText", { fg = "#a0522d" })
vim.api.nvim_set_hl(0, "TroubleCount", { fg = "#a0522d", bg = "#2d1810" })
vim.api.nvim_set_hl(0, "TroubleNormal", { fg = "#fff5e1", bg = "#1a0f0a" })

-- ── Plugin: Flash ──────────────────────────────────────────────────────
vim.api.nvim_set_hl(0, "FlashBackdrop", { fg = "#a0522d" })
vim.api.nvim_set_hl(0, "FlashLabel", { fg = "#fff5e1", bg = "#ef5350", bold = true })

-- ── Plugin: Grug-Far ───────────────────────────────────────────────────
vim.api.nvim_set_hl(0, "GrugFarHelpHeader", { fg = "#8b4513" })
vim.api.nvim_set_hl(0, "GrugFarHelpHeaderKey", { fg = "#f5a623" })
vim.api.nvim_set_hl(0, "GrugFarInputLabel", { fg = "#c4522a" })
vim.api.nvim_set_hl(0, "GrugFarInputPlaceholder", { fg = "#a0522d" })
vim.api.nvim_set_hl(0, "GrugFarResultsHeader", { fg = "#e87530" })
vim.api.nvim_set_hl(0, "GrugFarResultsMatch", { fg = "#0d0704", bg = "#ef5350" })
vim.api.nvim_set_hl(0, "GrugFarResultsStats", { fg = "#e87530" })
vim.api.nvim_set_hl(0, "GrugFarResultsLineNo", { fg = "#a0522d" })
vim.api.nvim_set_hl(0, "GrugFarResultsLineColumn", { fg = "#a0522d" })
vim.api.nvim_set_hl(0, "GrugFarResultsChangeIndicator", { fg = "#f5a623" })

-- ── Plugin: Bufferline ─────────────────────────────────────────────────
vim.api.nvim_set_hl(0, "BufferLineIndicatorSelected", { fg = "#f5a623" })

-- ── Plugin: Lazy ───────────────────────────────────────────────────────
vim.api.nvim_set_hl(0, "LazyProgressDone", { fg = "#ef5350", bold = true })
vim.api.nvim_set_hl(0, "LazyProgressTodo", { fg = "#2d1810", bold = true })

-- ── Plugin: Mini Icons ─────────────────────────────────────────────────
vim.api.nvim_set_hl(0, "MiniIconsAzure", { fg = "#f5a623" })
vim.api.nvim_set_hl(0, "MiniIconsBlue", { fg = "#e87530" })
vim.api.nvim_set_hl(0, "MiniIconsCyan", { fg = "#4caf50" })
vim.api.nvim_set_hl(0, "MiniIconsGreen", { fg = "#4caf50" })
vim.api.nvim_set_hl(0, "MiniIconsGrey", { fg = "#fff5e1" })
vim.api.nvim_set_hl(0, "MiniIconsOrange", { fg = "#e87530" })
vim.api.nvim_set_hl(0, "MiniIconsPurple", { fg = "#c4522a" })
vim.api.nvim_set_hl(0, "MiniIconsRed", { fg = "#ef5350" })
vim.api.nvim_set_hl(0, "MiniIconsYellow", { fg = "#e0af68" })

-- ── Terminal colors (vim.g.terminal_color_*) ────────────────────────────
vim.g.terminal_color_0  = "#0d0704"
vim.g.terminal_color_1  = "#ef5350"
vim.g.terminal_color_2  = "#4caf50"
vim.g.terminal_color_3  = "#f5a623"
vim.g.terminal_color_4  = "#e87530"
vim.g.terminal_color_5  = "#a0522d"
vim.g.terminal_color_6  = "#f5a623"
vim.g.terminal_color_7  = "#a0522d"
vim.g.terminal_color_8  = "#2d1810"
vim.g.terminal_color_9  = "#ef5350"
vim.g.terminal_color_10 = "#4caf50"
vim.g.terminal_color_11 = "#f5a623"
vim.g.terminal_color_12 = "#e87530"
vim.g.terminal_color_13 = "#c4522a"
vim.g.terminal_color_14 = "#fff5e1"
vim.g.terminal_color_15 = "#fff5e1"
