[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"

[[mgr.prepend_keymap]]
on   = "H"
run  = "plugin duckdb -1"
desc = "Scroll one column to the left (duckdb)"

[[mgr.prepend_keymap]]
on   = "L"
run  = "plugin duckdb +1"
desc = "Scroll one column to the right (duckdb)"

[[mgr.prepend_keymap]]
on   = [ "g", "o" ]
run  = "plugin duckdb -open"
desc = "Open with duckdb"

[[mgr.prepend_keymap]]
on   = [ "g", "u" ]
run  = "plugin duckdb -ui"
desc = "Open with duckdb UI"
