#!/bin/bash

# Theme switcher — reads a colors.toml palette and generates:
#   1. Sway client color variables (included by sway config)
#   2. Waybar CSS (replaces style.css)
# Then reloads sway and waybar.
#
# Usage:
#   theme list                — list available themes
#   theme set <name>          — apply a theme
#   theme current             — show current theme
#
# Themes live in ~/.config/omarchy-themes/*.toml (or the dotfiles source).
# Generated files go to ~/.local/state/theme-current/.
#
# Ported from Omarchy's theme system, adapted for Sway + waybar.

set -euo pipefail
export PATH="$HOME/.local/bin:$PATH"

THEMES_DIR="${THEMES_DIR:-$HOME/.config/omarchy-themes}"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/theme-current"
SWAY_COLORS="$STATE_DIR/sway-colors"
WAYBAR_CSS="$STATE_DIR/waybar-style.css"

mkdir -p "$STATE_DIR"

# ── TOML parser (reads key = "value" lines, extracts hex colors) ──
parse_toml() {
  local file="$1"
  declare -gA COLORS
  COLORS=()
  local line key value
  while IFS= read -r line; do
    # Only process lines that look like: key = "#hexcolor"
    [[ $line =~ ^([a-z_]+)[[:space:]]*=[[:space:]]*\"(#[0-9a-fA-F]+)\" ]] || continue
    key="${BASH_REMATCH[1]}"
    value="${BASH_REMATCH[2]}"
    COLORS[$key]="$value"
  done < "$file"
}

# ── List available themes ──
list_themes() {
  {
    find -L "$THEMES_DIR" -maxdepth 1 -name '*.toml' -printf '%f\n' 2>/dev/null
  } | sed 's/\.toml$//' | sort -u | sed -E 's/(^|-)([a-z])/\1\u\2/g; s/-/ /g'
}

# ── Generate Sway color variables from the parsed palette ──
# Maps colors.toml keys to the Yendo Cowboy Sway variable names:
#   background     -> $bg
#   darker_background -> $bg_darker
#   lighter_background -> $bg_mid
#   foreground     -> $fg
#   accent         -> $primary
#   bright_yellow  -> $accent  (falls back to yellow, then orange)
#   green          -> $ok
#   bright_red     -> $error
#   dark_foreground -> $dim
#   muted          -> $muted
#   $border        -> derived from accent (darkened)
#   $bg_tertiary   -> derived from lighter_background (lightened)
generate_sway_colors() {
  local bg="${COLORS[background]:-#1a1b26}"
  local bg_darker="${COLORS[darker_background]:-#0d0704}"
  local bg_mid="${COLORS[lighter_background]:-#2d1810}"
  local fg="${COLORS[foreground]:-#a9b1d6}"
  local primary="${COLORS[accent]:-#7aa2f7}"
  local accent="${COLORS[bright_yellow]:-${COLORS[yellow]:-${COLORS[orange]:-#f5a623}}}"
  local ok="${COLORS[green]:-#4caf50}"
  local error="${COLORS[bright_red]:-${COLORS[red]:-#ef5350}}"
  local dim="${COLORS[dark_foreground]:-#8b4513}"
  local muted="${COLORS[muted]:-#a0522d}"

  # Derive border from accent (just use accent, no darkening in bash)
  local border="$accent"

  # Derive bg_tertiary from bg_mid (use accent as a tertiary layer)
  local bg_tertiary="${COLORS[orange]:-${COLORS[bright_yellow]:-$primary}}"

  cat > "$SWAY_COLORS" << EOF
# Generated by theme switcher — do not edit manually
# Source: $(basename "${CURRENT_THEME_FILE:-unknown}")

set \$bg          $bg
set \$bg_darker   $bg_darker
set \$bg_mid      $bg_mid
set \$bg_tertiary $bg_tertiary
set \$fg          $fg
set \$primary     $primary
set \$accent      $accent
set \$border      $border
set \$ok          $ok
set \$error       $error
set \$dim         $dim
set \$muted       $muted

# Colors                border      backgr       text       indicator   child_border
client.focused          \$primary    \$primary     \$bg        \$accent     \$primary
client.focused_inactive \$muted      \$bg_mid      \$fg        \$border     \$muted
client.unfocused        \$dim        \$bg_darker   \$muted     \$border     \$dim
client.urgent           \$error      \$error       \$bg        \$error      \$error
client.placeholder      \$bg_mid     \$bg_mid      \$fg        \$accent     \$bg_mid
client.background       \$bg
EOF
}

# ── Generate waybar CSS from the parsed palette ──
# The waybar CSS uses a powerline segmented layout with these color roles:
#   workspaces bg    = bg_darker     workspaces focused = primary
#   network bg       = bg_mid         cpu bg = bg_tertiary
#   memory bg        = border         pulseaudio bg = primary
#   battery bg       = accent         clock bg = bg_darker
#   mise-updates bg  = ok (green)     mise-bumps bg = accent
#   nix-updates bg   = blue           tray bg = bg_mid
generate_waybar_css() {
  local bg="${COLORS[background]:-#1a1b26}"
  local bg_darker="${COLORS[darker_background]:-#0d0704}"
  local bg_mid="${COLORS[lighter_background]:-#2d1810}"
  local fg="${COLORS[foreground]:-#a9b1d6}"
  local primary="${COLORS[accent]:-#7aa2f7}"
  local accent="${COLORS[bright_yellow]:-${COLORS[yellow]:-${COLORS[orange]:-#f5a623}}}"
  local ok="${COLORS[green]:-#4caf50}"
  local error="${COLORS[bright_red]:-${COLORS[red]:-#ef5350}}"
  local dim="${COLORS[dark_foreground]:-#8b4513}"
  local muted="${COLORS[muted]:-#a0522d}"
  local border="$accent"
  local bg_tertiary="${COLORS[orange]:-${COLORS[bright_yellow]:-$primary}}"
  local blue="${COLORS[blue]:-#5e81ac}"

  cat > "$WAYBAR_CSS" << EOF
/* Generated by theme switcher — do not edit manually */
* {
    border: none;
    border-radius: 0;
    font-family: "DejaVuSansM Nerd Font Mono", "DejaVu Sans Mono";
    font-size: 10px;
    min-height: 0;
}

window#waybar {
    background-color: transparent;
    color: $fg;
}

#workspaces {
    background-color: $bg_darker;
    margin: 0;
    padding: 0;
}

#workspaces button {
    padding: 0 6px;
    color: $fg;
    background-color: $bg_darker;
}

#workspaces button.focused {
    background-color: $primary;
    color: $bg;
    border-bottom: 2px solid $accent;
}

#workspaces button.urgent {
    background-color: $error;
    color: $bg;
}

#workspaces button.visible {
    background-color: $bg_mid;
    color: $accent;
}

#mode {
    background-color: $accent;
    color: $bg;
    padding: 0 6px;
}

#network {
    background-color: $bg_mid;
    color: $fg;
    padding: 0 6px;
}

#network.disconnected {
    color: $muted;
}

#custom-left-cap,
#custom-sep-cpu,
#custom-sep-memory,
#custom-sep-pulseaudio,
#custom-sep-battery,
#custom-sep-date {
    font-size: 26px;
}

#custom-left-cap {
    color: $bg_mid;
    background-color: transparent;
    padding: 0;
    margin: 0;
}

#custom-sep-cpu {
    color: $bg_tertiary;
    background-color: $bg_mid;
    padding: 0;
    margin: 0;
}

#cpu {
    background-color: $bg_tertiary;
    color: $fg;
    padding: 0 6px;
}

#custom-sep-memory {
    color: $border;
    background-color: $bg_tertiary;
    padding: 0;
    margin: 0;
}

#memory {
    background-color: $border;
    color: $fg;
    padding: 0 6px;
}

#custom-sep-pulseaudio {
    color: $primary;
    background-color: $border;
    padding: 0;
    margin: 0;
}

#pulseaudio {
    background-color: $primary;
    color: $bg;
    padding: 0 6px;
}

#pulseaudio.muted {
    background-color: $muted;
    color: $bg;
}

#custom-sep-battery {
    color: $accent;
    background-color: $primary;
    padding: 0;
    margin: 0;
}

#battery {
    background-color: $accent;
    color: $bg;
    padding: 0 6px;
}

#battery.warning {
    background-color: $border;
}

#battery.critical {
    background-color: $error;
}

#custom-sep-date {
    color: $bg_darker;
    background-color: $accent;
    padding: 0;
    margin: 0;
}

#clock {
    background-color: $bg_darker;
    color: $fg;
    padding: 0 6px;
}

#custom-sep-mise {
    color: $ok;
    background-color: $bg_darker;
    font-size: 26px;
    padding: 0;
    margin: 0;
}

#custom-mise-updates {
    background-color: $ok;
    color: $bg;
    padding: 0 6px;
    font-weight: bold;
}

#custom-mise-updates.mise-updates-empty,
#custom-mise-updates.mise-updates-dismissed {
    background-color: transparent;
    padding: 0;
    margin: 0;
}

#custom-sep-bumps {
    color: $accent;
    background-color: $ok;
    font-size: 26px;
    padding: 0;
    margin: 0;
}

#custom-mise-bumps {
    background-color: $accent;
    color: $bg;
    padding: 0 6px;
    font-weight: bold;
}

#custom-mise-bumps.mise-bumps-empty,
#custom-mise-bumps.mise-bumps-dismissed {
    background-color: transparent;
    padding: 0;
    margin: 0;
}

#custom-mise-updates.mise-updates-empty ~ #custom-sep-bumps,
#custom-mise-updates.mise-updates-dismissed ~ #custom-sep-bumps {
    background-color: $bg_darker;
}

#custom-sep-nix {
    color: $blue;
    background-color: $accent;
    font-size: 26px;
    padding: 0;
    margin: 0;
}

#custom-nix-updates {
    background-color: $blue;
    color: $bg;
    padding: 0 6px;
    font-weight: bold;
}

#custom-nix-updates.nix-updates-empty,
#custom-nix-updates.nix-updates-dismissed {
    background-color: transparent;
    padding: 0;
    margin: 0;
}

#custom-mise-bumps.mise-bumps-empty ~ #custom-sep-nix,
#custom-mise-bumps.mise-bumps-dismissed ~ #custom-sep-nix {
    background-color: $bg_darker;
}

#tray {
    background-color: $bg_mid;
    padding: 0 4px;
}
EOF
}

# ── Apply a theme ──
apply_theme() {
  local theme_name="$1"
  local theme_file

  # Try exact match, then lowercase with spaces->hyphens
  local theme_lower="${theme_name,,}"
  theme_file="$THEMES_DIR/${theme_lower}.toml"
  if [[ ! -f $theme_file ]]; then
    theme_file="$THEMES_DIR/${theme_lower// /-}.toml"
  fi

  if [[ ! -f $theme_file ]]; then
    echo "Theme not found: $theme_name" >&2
    echo "Available themes:" >&2
    list_themes >&2
    exit 1
  fi

  CURRENT_THEME_FILE="$theme_file"
  parse_toml "$theme_file"
  generate_sway_colors
  generate_waybar_css

  # Save current theme name
  echo "${theme_name}" > "$STATE_DIR/current-theme"

  # Reload sway to pick up the new colors
  swaymsg reload 2>/dev/null || true

  # Restart waybar to pick up the new CSS
  # Kill existing waybar, start with the generated CSS
  pkill waybar 2>/dev/null || true
  sleep 0.3
  WAYBAR_CSS_PATH="$WAYBAR_CSS" waybar -s "$WAYBAR_CSS" &
  disown 2>/dev/null || true

  notify -g "Theme: $theme_name" -t 2000 2>/dev/null || true
}

# ── Show current theme ──
show_current() {
  if [[ -f $STATE_DIR/current-theme ]]; then
    cat "$STATE_DIR/current-theme"
  else
    echo "No theme set yet"
  fi
}

# ── Usage ──
usage() {
  echo "Usage: theme list | theme set <name> | theme current"
  echo ""
  echo "Available themes:"
  list_themes | sed 's/^/  /'
}

case "${1:-}" in
  list)
    list_themes
    ;;
  set)
    if [[ -z ${2:-} ]]; then
      echo "Usage: theme set <name>" >&2
      exit 1
    fi
    apply_theme "$2"
    ;;
  current)
    show_current
    ;;
  ""|--help|-h)
    usage
    ;;
  *)
    echo "Unknown command: $1" >&2
    usage
    exit 1
    ;;
esac
