#!/bin/bash

# Theme switcher — reads a colors.toml palette and generates:
#   1. Sway client color variables (included by sway config)
#   2. Waybar CSS (powerline segmented bar)
#   3. btop theme file (color_theme = "current")
#   4. Wezterm color overrides (dofile'd by wezterm.lua)
#   5. Ghostty color config (included by ghostty/config)
# Then reloads sway, waybar, wezterm, and btop.
#
# Usage:
#   theme list                — list available themes
#   theme set <name>          — apply a theme
#   theme current             — show current theme
#
# Themes live in ~/.config/omarchy-themes/*.toml
# Generated files go to ~/.local/state/theme-current/

set -euo pipefail
export PATH="$HOME/.local/bin:$PATH"

THEMES_DIR="${THEMES_DIR:-$HOME/.config/omarchy-themes}"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/theme-current"
SWAY_COLORS="$STATE_DIR/sway-colors"
WAYBAR_CSS="$STATE_DIR/waybar-style.css"
BTOP_THEME="$STATE_DIR/btop-current.theme"
WEZTERM_COLORS="$STATE_DIR/wezterm-colors.lua"
GHOSTTY_COLORS="$STATE_DIR/ghostty-colors.conf"

mkdir -p "$STATE_DIR"

# ── Resolve a color key with fallback chain ──
color() {
  local key="$1"
  local fallback="$2"
  printf '%s' "${COLORS[$key]:-$fallback}"
}

# ── TOML parser (reads key = "value" lines, extracts hex colors) ──
parse_toml() {
  local file="$1"
  declare -gA COLORS
  COLORS=()
  local line key value
  while IFS= read -r line; do
    [[ $line =~ ^([a-z_]+)[[:space:]]*=[[:space:]]*\"(#[0-9a-fA-F]+)\" ]] || continue
    key="${BASH_REMATCH[1]}"
    value="${BASH_REMATCH[2]}"
    COLORS[$key]="$value"
  done < "$file"
}

# ── List available themes ──
list_themes() {
  {
    find -L "$THEMES_DIR" -maxdepth 1 -name '*.toml' -printf '%f\n' 2>/dev/null
  } | sed 's/\.toml$//' | sort -u | sed -E 's/(^|-)([a-z])/\1\u\2/g; s/-/ /g'
}

# ── Generate Sway color variables ──
generate_sway_colors() {
  local bg=$(color background "#1a1b26")
  local bg_darker=$(color darker_background "#0d0704")
  local bg_mid=$(color lighter_background "#2d1810")
  local fg=$(color foreground "#a9b1d6")
  local primary=$(color accent "#7aa2f7")
  local _yellow=$(color yellow "#e0af68")
  local _orange=$(color orange "#e87530")
  local accent=$(color bright_yellow "$_yellow")
  [[ -z ${COLORS[bright_yellow]} ]] && accent=$(color bright_yellow "$_orange")
  local ok=$(color green "#4caf50")
  local _red=$(color red "#f7768e")
  local error=$(color bright_red "$_red")
  local dim=$(color dark_foreground "#8b4513")
  local muted=$(color muted "#a0522d")
  local border="$accent"
  local bg_tertiary=$(color orange "$_orange")

  cat > "$SWAY_COLORS" << EOF
# Generated by theme switcher — do not edit manually
# Source: ${CURRENT_THEME_NAME:-unknown}

set \$bg          $bg
set \$bg_darker   $bg_darker
set \$bg_mid      $bg_mid
set \$bg_tertiary $bg_tertiary
set \$fg          $fg
set \$primary     $primary
set \$accent      $accent
set \$border      $border
set \$ok          $ok
set \$error       $error
set \$dim         $dim
set \$muted       $muted

client.focused          \$primary    \$primary     \$bg        \$accent     \$primary
client.focused_inactive \$muted      \$bg_mid      \$fg        \$border     \$muted
client.unfocused        \$dim        \$bg_darker   \$muted     \$border     \$dim
client.urgent           \$error      \$error       \$bg        \$error      \$error
client.placeholder      \$bg_mid     \$bg_mid      \$fg        \$accent     \$bg_mid
client.background       \$bg
EOF
}

# ── Generate waybar CSS ──
generate_waybar_css() {
  local bg=$(color background "#1a1b26")
  local bg_darker=$(color darker_background "#0d0704")
  local bg_mid=$(color lighter_background "#2d1810")
  local fg=$(color foreground "#a9b1d6")
  local primary=$(color accent "#7aa2f7")
  local _yellow=$(color yellow "#e0af68")
  local _orange=$(color orange "#e87530")
  local accent=$(color bright_yellow "$_yellow")
  [[ -z ${COLORS[bright_yellow]} ]] && accent=$(color bright_yellow "$_orange")
  local ok=$(color green "#4caf50")
  local _red=$(color red "#f7768e")
  local error=$(color bright_red "$_red")
  local muted=$(color muted "#a0522d")
  local border="$accent"
  local bg_tertiary=$(color orange "$_orange")
  local blue=$(color blue "#5e81ac")

  cat > "$WAYBAR_CSS" << EOF
/* Generated by theme switcher — do not edit manually */
* {
    border: none;
    border-radius: 0;
    font-family: "DejaVuSansM Nerd Font Mono", "DejaVu Sans Mono";
    font-size: 10px;
    min-height: 0;
}

window#waybar {
    background-color: transparent;
    color: $fg;
}

#workspaces {
    background-color: $bg_darker;
    margin: 0;
    padding: 0;
}

#workspaces button {
    padding: 0 6px;
    color: $fg;
    background-color: $bg_darker;
}

#workspaces button.focused {
    background-color: $primary;
    color: $bg;
    border-bottom: 2px solid $accent;
}

#workspaces button.urgent {
    background-color: $error;
    color: $bg;
}

#workspaces button.visible {
    background-color: $bg_mid;
    color: $accent;
}

#mode {
    background-color: $accent;
    color: $bg;
    padding: 0 6px;
}

#network {
    background-color: $bg_mid;
    color: $fg;
    padding: 0 6px;
}

#network.disconnected {
    color: $muted;
}

#custom-left-cap,
#custom-sep-cpu,
#custom-sep-memory,
#custom-sep-pulseaudio,
#custom-sep-battery,
#custom-sep-date {
    font-size: 26px;
}

#custom-left-cap {
    color: $bg_mid;
    background-color: transparent;
    padding: 0;
    margin: 0;
}

#custom-sep-cpu {
    color: $bg_tertiary;
    background-color: $bg_mid;
    padding: 0;
    margin: 0;
}

#cpu {
    background-color: $bg_tertiary;
    color: $fg;
    padding: 0 6px;
}

#custom-sep-memory {
    color: $border;
    background-color: $bg_tertiary;
    padding: 0;
    margin: 0;
}

#memory {
    background-color: $border;
    color: $fg;
    padding: 0 6px;
}

#custom-sep-pulseaudio {
    color: $primary;
    background-color: $border;
    padding: 0;
    margin: 0;
}

#pulseaudio {
    background-color: $primary;
    color: $bg;
    padding: 0 6px;
}

#pulseaudio.muted {
    background-color: $muted;
    color: $bg;
}

#custom-sep-battery {
    color: $accent;
    background-color: $primary;
    padding: 0;
    margin: 0;
}

#battery {
    background-color: $accent;
    color: $bg;
    padding: 0 6px;
}

#battery.warning {
    background-color: $border;
}

#battery.critical {
    background-color: $error;
}

#custom-sep-date {
    color: $bg_darker;
    background-color: $accent;
    padding: 0;
    margin: 0;
}

#clock {
    background-color: $bg_darker;
    color: $fg;
    padding: 0 6px;
}

#custom-sep-mise {
    color: $ok;
    background-color: $bg_darker;
    font-size: 26px;
    padding: 0;
    margin: 0;
}

#custom-mise-updates {
    background-color: $ok;
    color: $bg;
    padding: 0 6px;
    font-weight: bold;
}

#custom-mise-updates.mise-updates-empty,
#custom-mise-updates.mise-updates-dismissed {
    background-color: transparent;
    padding: 0;
    margin: 0;
}

#custom-sep-bumps {
    color: $accent;
    background-color: $ok;
    font-size: 26px;
    padding: 0;
    margin: 0;
}

#custom-mise-bumps {
    background-color: $accent;
    color: $bg;
    padding: 0 6px;
    font-weight: bold;
}

#custom-mise-bumps.mise-bumps-empty,
#custom-mise-bumps.mise-bumps-dismissed {
    background-color: transparent;
    padding: 0;
    margin: 0;
}

#custom-mise-updates.mise-updates-empty ~ #custom-sep-bumps,
#custom-mise-updates.mise-updates-dismissed ~ #custom-sep-bumps {
    background-color: $bg_darker;
}

#custom-sep-nix {
    color: $blue;
    background-color: $accent;
    font-size: 26px;
    padding: 0;
    margin: 0;
}

#custom-nix-updates {
    background-color: $blue;
    color: $bg;
    padding: 0 6px;
    font-weight: bold;
}

#custom-nix-updates.nix-updates-empty,
#custom-nix-updates.nix-updates-dismissed {
    background-color: transparent;
    padding: 0;
    margin: 0;
}

#custom-mise-bumps.mise-bumps-empty ~ #custom-sep-nix,
#custom-mise-bumps.mise-bumps-dismissed ~ #custom-sep-nix {
    background-color: $bg_darker;
}

#tray {
    background-color: $bg_mid;
    padding: 0 4px;
}
EOF
}

# ── Generate btop theme file ──
generate_btop_theme() {
  local bg=$(color background "#1a1b26")
  local fg=$(color foreground "#a9b1d6")
  local primary=$(color accent "#7aa2f7")
  local _yellow=$(color yellow "#e0af68")
  local _orange=$(color orange "#e87530")
  local accent=$(color bright_yellow "$_yellow")
  [[ -z ${COLORS[bright_yellow]} ]] && accent=$(color bright_yellow "$_orange")
  local ok=$(color green "#4caf50")
  local _red=$(color red "#f7768e")
  local error=$(color bright_red "$_red")
  local muted=$(color muted "#a0522d")
  local dim=$(color dark_foreground "#8b4513")
  local selection=$(color selection "$bg")
  local light_fg=$(color light_foreground "$fg")
  local magenta=$(color magenta "#ad8ee6")
  local cyan=$(color cyan "#449dab")
  local blue=$(color blue "#7aa2f7")
  local red=$(color red "#f7768e")
  local yellow=$(color yellow "#e0af68")
  local light_bg=$(color lighter_background "$bg")
  local bright_fg=$(color bright_foreground "$fg")

  cat > "$BTOP_THEME" << EOF
# Generated by theme switcher — do not edit manually
# Source: ${CURRENT_THEME_NAME:-unknown}

theme[main_bg]="$bg"
theme[main_fg]="$fg"
theme[title]="$fg"
theme[hi_fg]="$accent"
theme[selected_bg]="$selection"
theme[selected_fg]="$accent"
theme[inactive_fg]="$muted"
theme[graph_text]="$light_fg"
theme[meter_bg]="$selection"
theme[proc_misc]="$light_fg"
theme[cpu_box]="$magenta"
theme[mem_box]="$ok"
theme[net_box]="$red"
theme[proc_box]="$accent"
theme[div_line]="$muted"
theme[temp_start]="$ok"
theme[temp_mid]="$yellow"
theme[temp_end]="$red"
theme[cpu_start]="$cyan"
theme[cpu_mid]="$blue"
theme[cpu_end]="$magenta"
theme[free_start]="$magenta"
theme[free_mid]="$blue"
theme[free_end]="$cyan"
theme[cached_start]="$blue"
theme[cached_mid]="$cyan"
theme[cached_end]="$magenta"
theme[available_start]="$yellow"
theme[available_mid]="$red"
theme[available_end]="$red"
theme[used_start]="$ok"
theme[used_mid]="$cyan"
theme[used_end]="$blue"
theme[download_start]="$yellow"
theme[download_mid]="$red"
theme[download_end]="$red"
theme[upload_start]="$ok"
theme[upload_mid]="$cyan"
theme[upload_end]="$blue"
theme[process_start]="$cyan"
theme[process_mid]="$blue"
theme[process_end]="$magenta"
theme[gradient_color_0]="$bg"
theme[gradient_color_1]="$light_bg"
theme[gradient_color_2]="$selection"
theme[gradient_color_3]="$muted"
theme[gradient_color_4]="$dim"
theme[gradient_color_5]="$fg"
theme[gradient_color_6]="$light_fg"
theme[gradient_color_7]="$bright_fg"
EOF
}

# ── Generate wezterm color overrides (Lua) ──
generate_wezterm_colors() {
  local bg=$(color background "#1a1b26")
  local fg=$(color foreground "#a9b1d6")
  local bright_fg=$(color bright_foreground "$fg")
  local selection_bg=$(color selection "$bg")
  local muted=$(color muted "#a0522d")
  local accent=$(color accent "$bg")
  local dark_fg=$(color dark_foreground "$fg")
  local dark_bg=$(color darker_background "$bg")
  local light_bg=$(color lighter_background "$bg")
  local red=$(color red "#f7768e")
  local green=$(color green "#9ece6a")
  local yellow=$(color yellow "#e0af68")
  local blue=$(color blue "#7aa2f7")
  local magenta=$(color magenta "#ad8ee6")
  local cyan=$(color cyan "#449dab")
  local bright_red=$(color bright_red "#ff7a93")
  local bright_green=$(color bright_green "#b9f27c")
  local bright_yellow=$(color bright_yellow "#ff9e64")
  local bright_blue=$(color bright_blue "#7da6ff")
  local bright_magenta=$(color bright_magenta "#bb9af7")
  local bright_cyan=$(color bright_cyan "#0db9d7")

  cat > "$WEZTERM_COLORS" << EOF
-- Generated by theme switcher — do not edit manually
-- Source: ${CURRENT_THEME_NAME:-unknown}
-- dofile'd by wezterm.lua to override colors at runtime.

return {
  foreground = '$fg',
  background = '$bg',
  cursor_bg = '$bright_fg',
  cursor_fg = '$bg',
  cursor_border = '$bright_fg',
  selection_fg = '$bright_fg',
  selection_bg = '$selection_bg',
  split = '$accent',
  compose_cursor = '$yellow',
  scrollbar_thumb = '$light_bg',
  tab_bar = {
    background = '$dark_bg',
    active_tab = {
      bg_color = '$accent',
      fg_color = '$bg',
      intensity = 'Bold',
    },
    inactive_tab = {
      bg_color = '$bg',
      fg_color = '$dark_fg',
    },
    inactive_tab_hover = {
      bg_color = '$light_bg',
      fg_color = '$fg',
    },
    new_tab = {
      bg_color = '$bg',
      fg_color = '$dark_fg',
    },
    new_tab_hover = {
      bg_color = '$light_bg',
      fg_color = '$fg',
    },
  },
  ansi = {
    '$bg', '$red', '$green', '$yellow',
    '$blue', '$magenta', '$cyan', '$fg',
  },
  brights = {
    '$muted', '$bright_red', '$bright_green', '$bright_yellow',
    '$bright_blue', '$bright_magenta', '$bright_cyan', '$bright_fg',
  },
}
EOF
}

# ── Generate ghostty color config ──
generate_ghostty_colors() {
  local bg=$(color background "#1a1b26")
  local fg=$(color foreground "#a9b1d6")
  local bright_fg=$(color bright_foreground "$fg")
  local selection_bg=$(color selection "$bg")
  local muted=$(color muted "#a0522d")
  local red=$(color red "#f7768e")
  local green=$(color green "#9ece6a")
  local yellow=$(color yellow "#e0af68")
  local blue=$(color blue "#7aa2f7")
  local magenta=$(color magenta "#ad8ee6")
  local cyan=$(color cyan "#449dab")
  local bright_red=$(color bright_red "#ff7a93")
  local bright_green=$(color bright_green "#b9f27c")
  local bright_yellow=$(color bright_yellow "#ff9e64")
  local bright_blue=$(color bright_blue "#7da6ff")
  local bright_magenta=$(color bright_magenta "#bb9af7")
  local bright_cyan=$(color bright_cyan "#0db9d7")

  cat > "$GHOSTTY_COLORS" << EOF
# Generated by theme switcher — do not edit manually
# Source: ${CURRENT_THEME_NAME:-unknown}
# Included by ghostty/config via config-file.

background = $bg
foreground = $fg
cursor-color = $bright_fg
selection-background = $selection_bg
selection-foreground = $bright_fg

palette = 0=$bg
palette = 1=$red
palette = 2=$green
palette = 3=$yellow
palette = 4=$blue
palette = 5=$magenta
palette = 6=$cyan
palette = 7=$fg
palette = 8=$muted
palette = 9=$bright_red
palette = 10=$bright_green
palette = 11=$bright_yellow
palette = 12=$bright_blue
palette = 13=$bright_magenta
palette = 14=$bright_cyan
palette = 15=$bright_fg
EOF
}

# ── Apply a theme ──
apply_theme() {
  local theme_name="$1"
  local theme_file

  local theme_lower="${theme_name,,}"
  theme_file="$THEMES_DIR/${theme_lower}.toml"
  if [[ ! -f $theme_file ]]; then
    theme_file="$THEMES_DIR/${theme_lower// /-}.toml"
  fi

  if [[ ! -f $theme_file ]]; then
    echo "Theme not found: $theme_name" >&2
    echo "Available themes:" >&2
    list_themes >&2
    exit 1
  fi

  CURRENT_THEME_FILE="$theme_file"
  CURRENT_THEME_NAME="$theme_name"
  parse_toml "$theme_file"

  generate_sway_colors
  generate_waybar_css
  generate_btop_theme
  generate_wezterm_colors
  generate_ghostty_colors

  echo "${theme_name}" > "$STATE_DIR/current-theme"

  # Copy btop theme so btop's color_theme = "current" can find it.
  # btop searches ~/.config/btop/themes/ for <name>.theme.
  # btop does not follow symlinks for theme files, so use a real copy.
  mkdir -p ~/.config/btop/themes
  cp "$BTOP_THEME" ~/.config/btop/themes/current.theme

  # Reload sway to pick up new colors
  swaymsg reload 2>/dev/null || true

  # Restart waybar with generated CSS
  pkill waybar 2>/dev/null || true
  sleep 0.3
  waybar -s "$WAYBAR_CSS" &
  disown 2>/dev/null || true

  # btop picks up theme from color_theme = "current" — no reload needed,
  # it reads the .theme file on next render. Running btop instances
  # will pick it up on next refresh.

  # Wezterm and ghostty do not support safe runtime config reload
  # (wezterm's sandboxed Lua crashes on dofile; ghostty may not
  # handle a missing config-file include). They will pick up new
  # theme colors on next launch/restart.

  notify -g "Theme: $theme_name" -t 2000 2>/dev/null || true
}

# ── Show current theme ──
show_current() {
  if [[ -f $STATE_DIR/current-theme ]]; then
    cat "$STATE_DIR/current-theme"
  else
    echo "No theme set yet"
  fi
}

# ── Usage ──
usage() {
  echo "Usage: theme list OR theme set <name> OR theme current"
  echo ""
  echo "Available themes:"
  list_themes | sed 's/^/  /'
}

case "${1:-}" in
  list)
    list_themes
    ;;
  set)
    if [[ -z ${2:-} ]]; then
      echo "Usage: theme set <name>" >&2
      exit 1
    fi
    apply_theme "$2"
    ;;
  current)
    show_current
    ;;
  ""|--help|-h)
    usage
    ;;
  *)
    echo "Unknown command: $1" >&2
    usage
    exit 1
    ;;
esac
